// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package chat_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAttachment = "attachment"

// Attachment 附件
type Attachment struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:附件ID" json:"id"`                     // 附件ID
	Filename  string         `gorm:"column:filename;not null;comment:附件名称" json:"filename"`                              // 附件名称
	Size      int64          `gorm:"column:size;not null;comment:附件大小：单位-字节（B）" json:"size"`                             // 附件大小：单位-字节（B）
	Type      string         `gorm:"column:type;not null;comment:类型content-type" json:"type"`                            // 类型content-type
	Extension string         `gorm:"column:extension;not null;comment:扩展名" json:"extension"`                             // 扩展名
	Path      string         `gorm:"column:path;not null;comment:文件的相对路径" json:"path"`                                   // 文件的相对路径
	UserID    int64          `gorm:"column:user_id;not null;comment:用户ID" json:"userId"`                                 // 用户ID
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deletedAt"`                                    // 删除时间
}

// TableName Attachment's table name
func (*Attachment) TableName() string {
	return TableNameAttachment
}
