// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package chat_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGroupUser = "group_user"

// GroupUser 聊天群用户
type GroupUser struct {
	ID               int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增" json:"id"`                          // 自增
	UserID           int64          `gorm:"column:user_id;not null;comment:用户ID" json:"user_id"`                                   // 用户ID
	GroupID          int64          `gorm:"column:group_id;not null;comment:聊天ID" json:"group_id"`                                 // 聊天ID
	CustomGroupTitle string         `gorm:"column:custom_group_title;not null;comment:自定义群 标题" json:"custom_group_title"`          // 自定义群 标题
	CustomNickname   string         `gorm:"column:custom_nickname;not null;comment:自定义个人在群的昵称" json:"custom_nickname"`             // 自定义个人在群的昵称
	IsMessageRemind  int32          `gorm:"column:is_message_remind;not null;comment:是否消息提醒：1-提醒；2-免打扰；" json:"is_message_remind"` // 是否消息提醒：1-提醒；2-免打扰；
	IsTop            int32          `gorm:"column:is_top;not null;comment:是否消息提醒：1-提醒；2-免打扰；" json:"is_top"`                       // 是否消息提醒：1-提醒；2-免打扰；
	IsTopTime        time.Time      `gorm:"column:is_top_time;comment:设置置顶时间" json:"is_top_time"`                                  // 设置置顶时间
	CreatedAt        time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`   // 创建时间
	UpdatedAt        time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"`   // 更新时间
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                      // 删除时间
}

// TableName GroupUser's table name
func (*GroupUser) TableName() string {
	return TableNameGroupUser
}
