// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package chat_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameGroup = "group"

// Group 聊天群
type Group struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增" json:"id"`                        // 自增
	Title         string         `gorm:"column:title;not null;comment:群聊名称" json:"title"`                                     // 群聊名称
	UserCount     int32          `gorm:"column:user_count;not null;comment:群聊用户总数" json:"user_count"`                         // 群聊用户总数
	CreatedUserID int64          `gorm:"column:created_user_id;not null;comment:群创建的用户ID" json:"created_user_id"`             // 群创建的用户ID
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
