// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package chat_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameMessage = "message"

// Message 消息
type Message struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增" json:"id"`                        // 自增
	Sender    int64          `gorm:"column:sender;not null;comment:消息发送人" json:"sender"`                                  // 消息发送人
	Type      string         `gorm:"column:type;not null;comment:消息类型" json:"type"`                                       // 消息类型
	Content   string         `gorm:"column:content;not null;comment:消息内容" json:"content"`                                 // 消息内容
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
