// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package chat_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRoom = "room"

// Room 聊天会话
type Room struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增" json:"id"`                       // 自增
	Title         string         `gorm:"column:title;not null;comment:聊天会话名称" json:"title"`                                  // 聊天会话名称
	Type          int32          `gorm:"column:type;not null;comment:聊天会话类型：1-私聊；2-群聊；" json:"type"`                         // 聊天会话类型：1-私聊；2-群聊；
	UserCount     int32          `gorm:"column:user_count;not null;comment:聊天会话用户总数" json:"userCount"`                       // 聊天会话用户总数
	LastMessageID int64          `gorm:"column:last_message_id;not null;comment:最后一条消息ID" json:"lastMessageId"`              // 最后一条消息ID
	CreatedUserID int64          `gorm:"column:created_user_id;not null;comment:创建的用户ID" json:"createdUserId"`               // 创建的用户ID
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createdAt"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updatedAt"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deletedAt"`                                    // 删除时间
}

// TableName Room's table name
func (*Room) TableName() string {
	return TableNameRoom
}
