// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package chat_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameRoomUser = "room_user"

// RoomUser 聊天会话用户
type RoomUser struct {
	ID              int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增" json:"id"`                        // 自增
	RoomID          int64          `gorm:"column:room_id;not null;comment:聊天会话ID" json:"roomId"`                                // 聊天会话ID
	UserID          int64          `gorm:"column:user_id;not null;comment:用户ID" json:"userId"`                                  // 用户ID
	CustomRoomTitle string         `gorm:"column:custom_room_title;not null;comment:自定义群 标题" json:"customRoomTitle"`            // 自定义群 标题
	CustomNickname  string         `gorm:"column:custom_nickname;not null;comment:自定义个人在群的昵称" json:"customNickname"`            // 自定义个人在群的昵称
	IsMessageRemind int32          `gorm:"column:is_message_remind;not null;comment:是否消息提醒：1-提醒；2-免打扰；" json:"isMessageRemind"` // 是否消息提醒：1-提醒；2-免打扰；
	IsTop           int32          `gorm:"column:is_top;not null;comment:是否置顶：1-是；2-否；" json:"isTop"`                           // 是否置顶：1-是；2-否；
	IsTopTime       time.Time      `gorm:"column:is_top_time;comment:设置置顶时间" json:"isTopTime"`                                  // 设置置顶时间
	CreatedAt       time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createdAt"`  // 创建时间
	UpdatedAt       time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updatedAt"`  // 更新时间
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deletedAt"`                                     // 删除时间
}

// TableName RoomUser's table name
func (*RoomUser) TableName() string {
	return TableNameRoomUser
}
