// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package chat_model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUser = "user"

// User 用户信息
type User struct {
	ID            int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:自增" json:"id"`                        // 自增
	Phone         string         `gorm:"column:phone;not null;comment:用户手机号" json:"phone"`                                    // 用户手机号
	UserName      string         `gorm:"column:user_name;not null;comment:用户名称" json:"user_name"`                             // 用户名称
	Nickname      string         `gorm:"column:nickname;not null;comment:用户昵称" json:"nickname"`                               // 用户昵称
	WxOpenid      string         `gorm:"column:wx_openid;not null;comment:微信openid" json:"wx_openid"`                         // 微信openid
	WxUnionid     string         `gorm:"column:wx_unionid;not null;comment:微信unionid" json:"wx_unionid"`                      // 微信unionid
	WxSessionKey  string         `gorm:"column:wx_session_key;not null;comment:微信会话密钥session_key" json:"wx_session_key"`      // 微信会话密钥session_key
	Gender        int32          `gorm:"column:gender;not null;default:-1;comment:性别" json:"gender"`                          // 性别
	Avatar        string         `gorm:"column:avatar;not null;comment:头像" json:"avatar"`                                     // 头像
	LastLoginTime time.Time      `gorm:"column:last_login_time;comment:最后登录时间" json:"last_login_time"`                        // 最后登录时间
	LastLoginIP   string         `gorm:"column:last_login_ip;comment:最后登录IP" json:"last_login_ip"`                            // 最后登录IP
	CreatedAt     time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt     time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt     gorm.DeletedAt `gorm:"column:deleted_at;comment:删除时间" json:"deleted_at"`                                    // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
